FROM oven/bun:1.1 as base

ENV DATABASE_URL="file:./dev.db"
ENV ORIGIN="http://localhost:5173"

FROM base as build
WORKDIR /temp
COPY . .
RUN bun install
RUN bun build:linux

FROM base as production
WORKDIR /app
COPY --from=build /temp/build ./
COPY --from=build /temp/prisma ./prisma
COPY --from=build /temp/package.json ./package.json
COPY --from=build /temp/node_modules ./node_modules

RUN bunx prisma generate
RUN bunx prisma db push --schema=/app/prisma/schema.prisma

EXPOSE 8080
ENTRYPOINT ["/app/discordfs"]